engines:
  eslint:
    enabled: true
  csslint:
    enabled: true
  phpcodesniffer:
    enabled: true
    config:
      standard: "Drupal"
  phpmd:
    enabled: true
  scss-lint:
    enabled: true
ratings:
  paths:
  - "**.inc"
  - "**.module"
  - "**.profile"
  - "**.php"
  - "**.install"
  - "**.js"
  - "**.css"
  - "**.scss"
##exclude these files/paths
exclude_paths:
- "**.features.**"
- "**.views_default.inc"
- "**.field_group.inc"
- "**.ds.inc"
- "**.bean.inc"
- "**.context.inc"
- "**.strongarm.inc"
