engines:
  eslint:
    enabled: true
  csslint:
    enabled: true
  phpcodesniffer:
    enabled: true
  phpmd:
    enabled: true
  scss-lint:
    enabled: true

##exclude these files/paths
exclude_paths:
  "**.feature"
