<?php
/**
 * @file
 * Code for the Stanford Page feature.
 */

include_once 'stanford_page.features.inc';

/**
 * Implements hook_theme_registry_alter().
 *
 * Scans and adds any tpl files within the module.
 * @see https://www.drupal.org/docs/7/creating-custom-modules/howtos/using-template-tplphp-files-in-your-own-module
 */
function stanford_page_theme_registry_alter(&$theme_registry) {
  $module_path = drupal_get_path('module', 'stanford_page');
  $template_file_objects = drupal_find_theme_templates($theme_registry, '.tpl.php', $module_path);
  foreach ($template_file_objects as $key => $template_file_object) {
    if (!isset($theme_registry[$key]['theme path']) || !preg_match('#/themes/#', $theme_registry[$key]['theme path'])) {
      $theme_registry[$key]['theme path'] = $module_path;
      $theme_registry[$key] = array_merge($theme_registry[$key], $template_file_object);
      $theme_registry[$key]['type'] = 'module';
    }
  }
}

/**
 * Implements hook_preprocess_HOOK().
 */
function stanford_page_preprocess_page(&$vars) {
  global $theme;
  if (isset($vars['node']) && $theme == variable_get('theme_default', 'seven')) {
    // Adds a new theme file per node type, such as page--node--article.tpl.php.
    $vars['theme_hook_suggestions'][] = 'page__node__' . $vars['node']->type;
  }
}

/**
 * Implements hook_preprocess_HOOK().
 */
function stanford_page_preprocess_node(&$vars) {
  if ($vars['type'] == 'stanford_page' && $vars['page']) {
    drupal_add_css(drupal_get_path('module', 'stanford_page') . '/css/stanford_page.css');
  }
}

/**
 * Implements hook_form_alter().
 */
function stanford_page_form_alter(&$form, &$form_state, $form_id) {
  if (strpos($form_id, '_node_form') !== FALSE && isset($form['field_s_page_sections'])) {
    foreach ($form['field_s_page_sections'][LANGUAGE_NONE] as &$section) {
      if ($section['#bundle'] == 'p_cards') {
        if ($section['field_p_cards_card']['und']['#max_delta'] == 2) {
          // Prevents more than 3 items.
          unset($section['field_p_cards_card']['und']['add_more']);
        }
      }
    }
  }
}
