<?php
/**
 * @file
 * File description.
 *
 * Long description.
 */

/**
 * Attach some CSS to the page.
 * @param  [type] $vars [description]
 * @return [type]       [description]
 */
function stanford_page_preprocess_page(&$vars) {

  // Get the node from the route.
  $node = \Drupal::routeMatch()->getParameter('node');

  // Not a node.. Then just continue.
  if (!$node) {
    return;
  }

  // Check for our type and add library if a match.
  if ($node->getType() == "stanford_page") {
    $vars['#attached']['library'][] = "stanford_page/page";
  }

}
